# Generated by Django 3.1.2 on 2020-10-27 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PreviewImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='PostImage'),
            preserve_default=False,
        ),
    ]
