# Generated by Django 3.1.2 on 2020-11-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201113_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
