# Generated by Django 3.1.2 on 2020-11-08 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=31, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('profilePicture', models.ImageField(upload_to='img/profile')),
                ('address', models.CharField(max_length=200, null=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('religion', models.CharField(max_length=200, null=True)),
                ('skype', models.CharField(max_length=50, null=True)),
                ('freelance', models.CharField(choices=[('Available', 'Available '), ('Unavailable', 'Unavailable')], max_length=50, null=True)),
                ('languages', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('resume', models.FileField(upload_to='files/resume')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
