# Generated by Django 3.1.3 on 2020-11-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('school', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('current', models.BooleanField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('current', models.BooleanField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, null=True)),
                ('client', models.CharField(max_length=150, null=True)),
                ('technologies', models.CharField(max_length=150, null=True)),
                ('preview_link', models.URLField(null=True)),
                ('portfolio_image', models.ImageField(default='placeholder.png', null=True, upload_to='img/ImagePortfolio')),
            ],
        ),
        migrations.CreateModel(
            name='LocalVidecPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, null=True)),
                ('client', models.CharField(max_length=150, null=True)),
                ('technologies', models.CharField(max_length=150, null=True)),
                ('video_file', models.FileField(upload_to='static/LocalVideos')),
                ('preview_link', models.URLField(null=True)),
                ('preview_image', models.ImageField(null=True, upload_to='img/LocalVideoImage')),
            ],
        ),
        migrations.CreateModel(
            name='SliderPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, null=True)),
                ('client', models.CharField(max_length=150, null=True)),
                ('technologies', models.CharField(max_length=150, null=True)),
                ('preview_link', models.URLField(null=True)),
                ('preview_image', models.ImageField(null=True, upload_to='img/slider')),
                ('portfolio_image1', models.ImageField(null=True, upload_to='img/slider')),
                ('portfolio_image2', models.ImageField(null=True, upload_to='img/slider')),
                ('portfolio_image3', models.ImageField(null=True, upload_to='img/slider')),
                ('portfolio_image4', models.ImageField(null=True, upload_to='img/slider')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('github', 'github'), ('linkedin', 'linkedin'), ('behance', 'behance'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('youtube', 'youtube')], max_length=200, null=True)),
                ('social_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('years_of_experience', models.IntegerField(null=True)),
                ('projects_completed', models.IntegerField(null=True)),
                ('happy_clients', models.IntegerField(null=True)),
                ('awards_won', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideoPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, null=True)),
                ('client', models.CharField(max_length=150, null=True)),
                ('technologies', models.CharField(max_length=150, null=True)),
                ('preview_link', models.URLField(null=True)),
                ('youtube_imbed_code', models.CharField(max_length=1000, null=True)),
                ('preview_image', models.ImageField(null=True, upload_to='img/YoutubePreview')),
            ],
        ),
    ]
