# Generated by Django 3.1.3 on 2020-11-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_experience_imageportfolio_localvidecportfolio_sliderportfolio_social_stat_youtubevideoport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalVidecPortfolio',
            new_name='LocalVideoPortfolio',
        ),
    ]
