# Generated by Django 3.1.3 on 2020-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20201108_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='current',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
