# Generated by Django 3.1.3 on 2020-11-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20201108_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
