# Generated by Django 3.1.3 on 2020-11-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20201108_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='health',
            field=models.CharField(default='ok', max_length=50, null=True),
        ),
    ]
