# Generated by Django 3.1.3 on 2020-11-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_person_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(null=True),
        ),
    ]
