# Generated by Django 3.1.3 on 2020-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20201109_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='current',
            field=models.BooleanField(null=True),
        ),
    ]
