# Generated by Django 3.1.3 on 2020-11-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20201109_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='full_name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
