# Generated by Django 3.1.3 on 2020-11-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20201109_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localvideoportfolio',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='video/LocalVideoImage'),
        ),
    ]
