# Generated by Django 3.1.3 on 2020-11-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20201113_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageportfolio',
            name='portfolio_image',
            field=models.ImageField(default='placeholder.png', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='person',
            name='health',
            field=models.CharField(default='Excellent', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profilePicture',
            field=models.ImageField(upload_to='img'),
        ),
    ]
