# Generated by Django 3.1.3 on 2020-11-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20201113_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
    ]
